version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Getting Started
  pre_build:
    commands:
      - echo Installing source NPM dependencies..
      - npm install
      - aws --version
  build:
    commnads:
      - echo Build started on 'date'
      - echo first test codes
      - CI=true npm test
      - echo Compiling the codes
      - npm run build
      - echo Build finished
   post_build:
     commands:
       - echo Build completed on 'date'
